export const SET_QUESTIONS = 'SET_QUESTIONS'
export const SET_NUMBER_OF_QUESTIONS = 'SET_NUMBER_OF_QUESTIONS'
export const SET_DIFFICULTIES = 'SET_DIFFICULTIES'
export const SET_CATEGORIES = 'SET_CATEGORIES'